### ISSUE TITLE
User should have a nav bar available in all sections

### ISSUE THREAD

**Issue by Nolan-Little** [garrulous-gobies/Bangazon_1#17]
**Given** the user wants to navigate to a different section
**When** the user performs a gesture on an appropriate nav bar affordance 
**Then** the user will be presented with the appropriate view

##Non-mandatory Testing Criteria

*your test suite must verify when a GET operation is performed to the corresponding affordance URL , then a successful response is received. Status code must be 200.

**Comment by braddavistech** [comment]
Completed NavBar setup and linked to html pages. Entire team reviewed PR and gave 👍 .
